### ISSUE TITLE
Renomear projeto?

### ISSUE THREAD

**Issue by Atsocs** [Magicos-de-CES-22/proj2#11]
# Motivação
Como podem ver na imagem abaixo, o nome é esteticamente feio quando ITA é utilizado em maiúsculas, como é usual em **nomITAs** (btw, alguém sabe se existe alguma lista de nomITAs? poderia ter um artigo da wikITA sobre isso).

![image](https://user-images.githubusercontent.com/24798860/118063267-21846a80-b36f-11eb-95ef-cd3b572463ea.png)

Aceitando sugestões de nomes aqui nessa issue, quem gostar reage com emojis (no canto superior direito)

**Comment by samuelv8** [comment]
Mudar a fonte pode resolver também (uma fonte com serifa, por exemplo).
