### ISSUE TITLE
Mágicos R3

### ISSUE THREAD

**Issue by Atsocs** [Magicos-de-CES-22/proj2#6]
Próxima reunião em grupo:
0 - Cada um ao longo da semana traz um desenho da sua visualização pra tela do avalita (issue #9), tendo em vista as features discutidas na R2 (issue #4). Veja componentes no [vuetify](https://vuetifyjs.com/en/).

1 - Atualizar sobre o que foi feito (5 min)
- ambiente docker configurado - GM
- deploy - SAC

2 - Design da(s) tela(s) do app com alguma ferramenta (15 min)
- faltou contribuição nas ideias pro front em #9 (ponto 0 acima), põe mais tempo de reunião para ideação agora?
-  [Link p/ Jamboard](https://jamboard.google.com/d/1T3UI-yeRxVBle5PWUsrDMSi-e9zoLC2bRV_at4Z2WRA/edit?usp=sharing)

3 - Distribuição de tarefas do front end a partir das funcionalidades e/ou páginas (10 min)
- decidir definitivamente quais serão (5 min)
  - issue #7
  - pull request #14 
- e quem ficará com quais (5 min)

4 - Criar nova issue para a próxima reunião R4
- Atividade postada no classroom hj (18/05) ?

**podem adicionar algo abaixo nos comentários :smile: (manda msg no grupo tb pf)**

_Originally posted by @skinnymega in https://github.com/Magicos-de-CES-22/proj2/issues/4#issuecomment-840097516_

**Comment by Atsocs** [comment]
Horário definido e fixado para as próximas reuniões semanais (terças 5:00 – 5:30pm)
> Mágicos R3
> Tuesday, May 18 · 5:00 – 5:30pm
> Google Meet joining info
> Video call link: https://meet.google.com/jfs-zfgg-dsm

**Comment by skinnymega** [comment]
Ata:

1 - GM: Erro de comunicação, ambiente para desenvolvimento bastava todos baixarem e dar clone. 
SAC: Deploy foi feito com base no macaco do heroku, a partir do ambiente do Git, não Docker. 

GM - vão fazer um docs para bizurar o resto do grupo com relação ao uso do Docker

2 - Designs apresentados, decidir como fazer: 

GM: PAG. 0 + PAG DO GAGA
SAC: PAGINA DO KAN BAN

-> PAGINA 0 -> HOMEPAGE DO BIS + LOGIN
-> FEZ LOGIN -> PAGINA COM KAN BAN DE DPTOS INTERATIVO + ABRE O KAN BAN PRA CADA DPTO COM DISCIPLINAS
-> DISCIPLINAS SÃO TOGGLE LISTS QUE O USER PODE ABRIR E ESCOLHER UM PROFESSOR 
-> VER AVALIAÇÃO DA DISCIPLINA (Pop-up/pagina).
-> PÁGINA COM BOTÃO DE ADICIONAR AVALIAÇÃO -> COLOCA SEMESTRE E A PAGINA AGRUPA POR SEMESTRE AS DISCIPLINAS (PAG. DO GAGA)

-> Del vai fazer os desenhos para todos visualizarem a mesma coisa. 

Próxima reunião: atualizar sobre paginas programadas do front-end; Dividir próximos passos de features que integrem com back-end; Lembrar do UML;

**Comment by Atsocs** [comment]
[Design da Marina](https://www.canva.com/design/DAEe3iKSwAA/3q9rjoJJJohZG6jQhrLkAg/view?utm_content=DAEe3iKSwAA&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton#1) - a ser aprovado até amanhã (19/05)
